/* MIZU MATCHA — single-entry frontend. Sections: utils, art, state, layout, pages, motion. */
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>'$'+n.toFixed(2),stars=r=>'★'.repeat(Math.round(r))+'☆'.repeat(5-Math.round(r));
const db={get:k=>{try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}},set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const byId=id=>PRODUCTS.find(p=>p.id==id);
/* ---------- generated artwork (consistent muted palette) ---------- */
const BG=['#E4DAC6','#DCE0C8','#EAE2D0','#D6CBB2'];
function art(p,v=0,cls=''){const c=p.c,i=p.item,bg=BG[v%4];let g='';
 if(i==='bowl'||(i==='whisk'&&v==1)||v==1)g=`<ellipse cx="200" cy="300" rx="130" ry="26" fill="${i==='bowl'?c:'#EFE8D8'}"/><path d="M70 300q10 120 130 120t130-120z" fill="${i==='bowl'?c:'#F8F4EA'}"/><ellipse cx="200" cy="300" rx="112" ry="19" fill="#7E9444"/><path d="M130 300q70 14 140 0" stroke="#A9B592" fill="none" stroke-width="3"/>`;
 else if(i==='whisk'||v==2)g=`<g class="${cls}"><rect x="188" y="80" width="24" height="140" rx="8" fill="#C9AE80"/><path d="M188 220q-40 40-34 130h92q6-90-34-130z" fill="#E1CCA1"/>${[0,1,2,3,4,5].map(k=>`<path d="M${164+k*14} 340Q200 240 200 222" stroke="#B89B6A" fill="none"/>`).join('')}</g>`;
 else if(v==3)g=`<ellipse cx="200" cy="380" rx="140" ry="30" fill="#D0C4A8"/><path d="M90 380q110-190 220 0z" fill="${c}"/><path d="M130 360q70-110 140 0" stroke="#fff" opacity=".18" fill="none" stroke-width="6"/>`;
 else g=`<ellipse cx="200" cy="420" rx="110" ry="14" fill="rgba(35,33,29,.18)"/><rect x="110" y="120" width="180" height="290" rx="14" fill="${c}"/><rect x="110" y="120" width="180" height="46" rx="14" fill="#23211D"/><rect x="132" y="210" width="136" height="150" fill="#F6F2E9"/><text x="200" y="255" text-anchor="middle" font-family="Cormorant Garamond,serif" font-size="22" letter-spacing="5" fill="#23211D">MIZU</text><text x="200" y="295" text-anchor="middle" font-family="Manrope,sans-serif" font-size="10" fill="#23211D">${p.name.slice(0,22)}</text><circle cx="200" cy="335" r="10" fill="${c}"/>`;
 return `<svg viewBox="0 0 400 500" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${p.name} product illustration"><rect width="400" height="500" fill="${bg}"/>${g}</svg>`}
const scene=(c,k)=>`<svg viewBox="0 0 400 500" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="400" height="500" fill="#E4DAC6"/>${k}</svg>`;
const SCENES={bowl:c=>scene(c,`<path d="M60 300q10 130 140 130t140-130z" fill="#4A3B30"/><ellipse cx="200" cy="300" rx="140" ry="28" fill="#4A3B30"/><ellipse cx="200" cy="300" rx="120" ry="20" fill="${c}"/>`),
 hills:c=>scene(c,`<path d="M0 330Q100 230 200 310T400 270V500H0z" fill="#A9B592"/><path d="M0 400Q120 320 230 380T400 350V500H0z" fill="${c}"/><circle cx="300" cy="120" r="44" fill="#F6F2E9"/>`),
 leaf:c=>scene(c,`<path d="M200 90Q330 220 200 420Q70 220 200 90z" fill="${c}"/><path d="M200 120V400" stroke="#F6F2E9" opacity=".5" stroke-width="2"/>`)};
const heroArt=()=>SCENES.bowl('#66793A');
/* ---------- state ---------- */
const cart={get:()=>db.get('mizu-cart'),set(v){db.set('mizu-cart',v);badges()},
 add(id,qty=1,size='30g'){const c=this.get(),l=c.find(x=>x.id==id&&x.size==size);l?l.qty+=qty:c.push({id,qty,size});this.set(c);const b=$('#cartBtn');b.classList.remove('bump');void b.offsetWidth;b.classList.add('bump');toast('Added to your ritual.')}};
const wish={get:()=>db.get('mizu-wish'),has:id=>wish.get().includes(+id),toggle(id){let w=wish.get();id=+id;if(w.includes(id)){w=w.filter(x=>x!=id);toast('Removed from your wishlist.')}else{w.push(id);toast('Saved to your wishlist.')}db.set('mizu-wish',w);badges();$$(`[data-wish="${id}"]`).forEach(b=>{b.classList.toggle('on',w.includes(id));b.textContent=w.includes(id)?'♥':'♡';b.setAttribute('aria-pressed',w.includes(id))})}};
function badges(){const c=cart.get().reduce((a,l)=>a+l.qty,0),w=wish.get().length;$('#cartCnt').textContent=c;$('#wishCnt').textContent=w;$('#cartCnt').hidden=!c;$('#wishCnt').hidden=!w}
let tt;function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),2200)}
/* ---------- layout ---------- */
const NAV=[['SHOP','shop.html'],['OUR STORY','story.html'],['RITUAL','ritual.html'],['RECIPES','recipes.html'],['CONTACT','story.html#contact']];
const ic=d=>`<svg viewBox="0 0 24 24" aria-hidden="true">${d}</svg>`;
function layout(){const page=document.body.dataset.page;
 $('#hdr').outerHTML=`<header class="hdr" id="hdr"><div class="wrap in"><a class="logo" href="index.html" aria-label="MIZU MATCHA home">MIZU MATCHA</a>
 <nav class="nav" id="nav" aria-label="Main">${NAV.map(([n,h])=>`<a href="${h}" ${h.startsWith(page)&&!h.includes('#')?'aria-current="page"':''}>${n}</a>`).join('')}</nav>
 <div class="icons"><button class="ib" id="sBtn" aria-label="Search">${ic('<circle cx="11" cy="11" r="6.5"/><path d="M16 16l5 5"/>')}</button>
 <a class="ib hide-m" href="story.html#contact" aria-label="Account">${ic('<circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 15-5 16 0"/>')}</a>
 <a class="ib hide-m" href="shop.html?wish=1" aria-label="Wishlist">${ic('<path d="M12 20S4 14.5 4 9a4.3 4.3 0 018-2 4.3 4.3 0 018 2c0 5.500-8 11-8 11z"/>')}<span class="cnt" id="wishCnt" hidden>0</span></a>
 <a class="ib" id="cartBtn" href="cart.html" aria-label="Cart">${ic('<path d="M5 8h14l-1 12H6z"/><path d="M9 8a3 3 0 016 0"/>')}<span class="cnt" id="cartCnt" hidden>0</span></a>
 <button class="ib burger" id="burger" aria-label="Menu" aria-expanded="false" aria-controls="nav"><span><i></i><i></i><i></i></span></button></div></div></header><div class="ov" id="ov"></div>`;
 $('#ftr').outerHTML=`<footer class="ftr"><div class="wrap"><div class="cols"><div><p class="logo">MIZU MATCHA</p><p class="muted small" style="margin-top:1rem;max-width:22rem;opacity:.7">A ritual worth slowing down for. Ceremonial Japanese matcha, delivered fresh.</p></div>
 <div><h3>Shop</h3><a href="shop.html">All matcha</a><a href="shop.html#accessories">Accessories</a><a href="cart.html">Cart</a></div><div><h3>Learn</h3><a href="story.html">Our story</a><a href="ritual.html">The ritual</a><a href="recipes.html">Recipes</a></div><div><h3>Help</h3><a href="story.html#contact">Contact</a><a href="story.html#faq">FAQ</a><a href="story.html#faq">Shipping</a></div></div><p class="copy">© 2026 MIZU MATCHA. A college web-development project.</p></div></footer>
 <div class="srch" id="srch" role="dialog" aria-modal="true" aria-label="Search"><button class="ib x" id="sx" aria-label="Close search">✕</button><div class="wrap"><input id="sq" type="search" placeholder="Search matcha, whisks, bowls" aria-label="Search products" autocomplete="off"><div class="grid" id="sres"></div></div></div>
 <div class="toast" id="toast" role="status" aria-live="polite"></div><button class="ib top" id="top" aria-label="Back to top">↑</button>`}
function behaviours(){const h=$('#hdr'),top=$('#top');
 const onS=()=>{h.classList.toggle('stuck',scrollY>20);top.classList.toggle('show',scrollY>700);const a=$('.arch[data-par]');if(a&&!matchMedia('(prefers-reduced-motion:reduce)').matches)a.style.transform=`translateY(${Math.min(scrollY*.08,60)}px)`;const pg=$('.prog');if(pg)pg.style.width=(scrollY/(document.body.scrollHeight-innerHeight)*100)+'%'};
 addEventListener('scroll',onS,{passive:true});onS();top.onclick=()=>scrollTo({top:0});
 const menu=o=>{document.body.classList.toggle('menu-open',o);$('#burger').setAttribute('aria-expanded',o)};
 $('#burger').onclick=()=>menu(!document.body.classList.contains('menu-open'));$('#ov').onclick=()=>menu(false);$$('#nav a').forEach(a=>a.onclick=()=>menu(false));
 const S=$('#srch'),q=$('#sq'),render=()=>{const t=q.value.trim().toLowerCase(),l=PRODUCTS.filter(p=>!t||(p.name+p.cat).toLowerCase().includes(t)).slice(0,t?8:4);$('#sres').innerHTML=l.length?l.map(card).join(''):'<p class="muted">No matches. Try “ceremonial” or “whisk”.</p>'};
 const sOpen=o=>{S.classList.toggle('open',o);if(o){render();setTimeout(()=>q.focus(),200)}};$('#sBtn').onclick=()=>sOpen(true);$('#sx').onclick=()=>sOpen(false);q.oninput=render;
 addEventListener('keydown',e=>{if(e.key==='Escape'){menu(false);sOpen(false);closeModal()}});
 document.addEventListener('click',e=>{const w=e.target.closest('[data-wish]'),a=e.target.closest('[data-add]');if(w){e.preventDefault();wish.toggle(w.dataset.wish)}if(a){e.preventDefault();cart.add(+a.dataset.add)}})}
/* ---------- components ---------- */
function card(p){const on=wish.has(p.id);return `<article class="card"><div class="media"><a href="product.html?id=${p.id}" aria-label="View ${p.name}" style="position:absolute;inset:0;z-index:1"></a>${p.badge?`<span class="badge">${p.badge}</span>`:''}<span class="a">${art(p,0)}</span>${art(p,p.item?2:3).replace('<svg','<svg class="b"')}<button class="wish ${on?'on':''}" data-wish="${p.id}" aria-pressed="${on}" aria-label="Save ${p.name} to wishlist">${on?'♥':'♡'}</button><div class="quick"><button class="btn sm" data-add="${p.id}">Add to cart <span>→</span></button></div></div>
<div class="info"><div><h3>${p.name}</h3><p class="small muted">${p.cat}</p><p class="stars" aria-label="${p.rating} out of 5">${stars(p.rating)} <span class="muted">${p.rating}</span></p></div><p>${money(p.price)}</p></div></article>`}
const grid=(el,l)=>{el.innerHTML=l.length?l.map(card).join(''):'<p class="muted">No products match. Clear a filter to see more.</p>'};
/* ---------- pages ---------- */
const pages={
home(){$('#heroArt').innerHTML=heroArt();grid($('#feat'),PRODUCTS.slice(0,4));grid($('#best'),PRODUCTS.filter(p=>p.badge==='Bestseller'||p.rating>=4.8).slice(0,4));
 $('#origin').innerHTML=SCENES.hills('#66793A')},
shop(){const st={cat:'All',sort:'featured',q:'',wish:false};const u=new URLSearchParams(location.search);if(u.get('wish'))st.wish=true;if(u.get('q'))st.q=u.get('q');
 if(location.hash==='#accessories')st.cat='Accessories';
 $('#chips').innerHTML=['All',...CATS].map(c=>`<button class="chip" data-c="${c}" aria-pressed="false">${c}</button>`).join('');
 const run=()=>{let l=PRODUCTS.filter(p=>(st.cat==='All'||p.cat===st.cat)&&(!st.q||(p.name+p.cat).toLowerCase().includes(st.q.toLowerCase()))&&(!st.wish||wish.has(p.id)));
  if(st.sort==='low')l.sort((a,b)=>a.price-b.price);if(st.sort==='high')l.sort((a,b)=>b.price-a.price);if(st.sort==='new')l.sort((a,b)=>b.id-a.id);
  grid($('#shopGrid'),l);$$('.chip').forEach(c=>{const on=c.dataset.c===st.cat;c.classList.toggle('on',on);c.setAttribute('aria-pressed',on)});$('#count').textContent=l.length+' products'+(st.wish?' in your wishlist':'')};
 $('#chips').onclick=e=>{const c=e.target.closest('.chip');if(c){st.cat=c.dataset.c;st.wish=false;run()}};$('#sort').onchange=e=>{st.sort=e.target.value;run()};$('#fq').value=st.q;$('#fq').oninput=e=>{st.q=e.target.value;run()};
 $('#ftog').onclick=e=>{const o=$('#panel').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',o)};run()},
product(){const p=byId(new URLSearchParams(location.search).get('id'))||PRODUCTS[0];document.title=p.name+' — MIZU MATCHA';
 const views=[0,1,2,3];let size='30g',q=1;const price=()=>p.price*SIZES[size];
 $('#pd').innerHTML=`<div class="gal"><div class="main" id="main">${art(p,0)}</div><div class="thumbs">${views.map(v=>`<button class="${v?'':'on'}" data-v="${v}" aria-label="View image ${v+1}">${art(p,v)}</button>`).join('')}</div></div>
 <div><p class="eyebrow muted">${p.cat}</p><h1 style="font-size:clamp(2.4rem,5vw,4rem);margin-block:.6rem">${p.name}</h1><p class="stars">${stars(p.rating)} <span class="muted">${p.rating} · 128 reviews</span></p><p style="font:400 2rem var(--serif);margin-top:1rem" id="pp">${money(price())}</p><p class="lead muted" style="margin-top:1rem">${p.desc} Whisked fresh, it tastes of sweet grass, cream and a quiet finish.</p>
 <div class="opts" role="group" aria-label="Size">${Object.keys(SIZES).map(s=>`<button class="chip ${s===size?'on':''}" data-s="${s}">${s}</button>`).join('')}</div>
 <div class="buy"><div class="qty"><button id="m" aria-label="Decrease quantity">−</button><output id="q" aria-live="polite">1</output><button id="pl" aria-label="Increase quantity">+</button></div><button class="btn" id="add">Add to cart <span>→</span></button><button class="btn ghost" id="now">Buy now</button><button class="ib wish on-p" style="position:static;opacity:1;border:1px solid var(--line)" data-wish="${p.id}" aria-pressed="${wish.has(p.id)}" aria-label="Save to wishlist">${wish.has(p.id)?'♥':'♡'}</button></div>
 <details open><summary>Shipping</summary><p>Free over $60. Ships from Kyoto in 2 business days; arrives in 4–7 days.</p></details><details><summary>Ingredients</summary><p>100% shade-grown Japanese green tea leaf, stone-ground. Nothing else.</p></details><details><summary>Origin</summary><p>Uji, Kyoto Prefecture. Harvested in May from tea shaded for 3 weeks.</p></details><details><summary>Preparation</summary><p>Sift 2g into a bowl, add 70ml water at 75°C, whisk in a W motion for 15 seconds.</p></details></div>`;
 $('.thumbs').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('.thumbs button').forEach(x=>x.classList.toggle('on',x===b));const m=$('#main');m.classList.add('sw');setTimeout(()=>{m.innerHTML=art(p,+b.dataset.v);m.classList.remove('sw')},300)};
 $('.opts').onclick=e=>{const b=e.target.closest('[data-s]');if(b){size=b.dataset.s;$$('.opts .chip').forEach(x=>x.classList.toggle('on',x===b));$('#pp').textContent=money(price())}};
 $('#m').onclick=()=>$('#q').textContent=q=Math.max(1,q-1);$('#pl').onclick=()=>$('#q').textContent=q=Math.min(20,q+1);
 $('#add').onclick=()=>cart.add(p.id,q,size);$('#now').onclick=()=>{cart.add(p.id,q,size);setTimeout(()=>location.href='cart.html',500)};
 $('#rev').innerHTML=[['Hana','Silky and sweet. No bitterness at all.'],['Marcus','Best bowl I have had outside Japan.'],['Priya','Lovely in lattes too. The colour is vivid.']].map(r=>`<blockquote style="padding-block:1rem;border-bottom:1px solid var(--line)"><p class="stars">★★★★★</p><p>${r[1]}</p><p class="small muted">${r[0]}, verified buyer</p></blockquote>`).join('');
 grid($('#rel'),PRODUCTS.filter(x=>x.cat===p.cat&&x.id!==p.id).concat(PRODUCTS.filter(x=>x.cat!==p.cat)).slice(0,4))},
cart(){const root=$('#cartRoot');let promo=db.get('mizu-promo')[0]||'';
 const draw=()=>{const c=cart.get();if(!c.length){root.innerHTML='<div class="empty"><h2>Your ritual is waiting.</h2><a class="btn" href="shop.html">Explore matcha <span>→</span></a></div>';return}
  const sub=c.reduce((a,l)=>a+byId(l.id).price*SIZES[l.size]*l.qty,0),disc=promo==='MIZU10'?sub*.1:0,ship=sub-disc>=60?0:6,tot=sub-disc+ship;
  root.innerHTML=`<div class="cl"><div>${c.map((l,i)=>{const p=byId(l.id);return `<div class="line"><div class="th">${art(p,0)}</div><div><h3>${p.name}</h3><p class="small muted">${l.size} · ${money(p.price*SIZES[l.size])}</p></div><div class="qty"><button data-i="${i}" data-d="-1" aria-label="Decrease ${p.name}">−</button><output>${l.qty}</output><button data-i="${i}" data-d="1" aria-label="Increase ${p.name}">+</button></div><div><p>${money(p.price*SIZES[l.size]*l.qty)}</p><button class="lk" data-r="${i}">Remove</button></div></div>`}).join('')}</div>
  <aside class="sum" aria-label="Order summary"><h2 style="font-size:2rem">Summary</h2><div><span>Subtotal</span><span>${money(sub)}</span></div><div><span>Discount</span><span>−${money(disc)}</span></div><div><span>Shipping</span><span>${ship?money(ship):'Free'}</span></div><div class="tot"><span>Total</span><span>${money(tot)}</span></div>
  <form id="pf" style="display:flex;gap:.5rem;margin-block:1rem"><input id="pc" placeholder="Promo code (try MIZU10)" aria-label="Promo code" value="${promo}"><button class="btn ghost sm">Apply</button></form><button class="btn full" id="co">Checkout <span>→</span></button></aside></div>`;
  $('#pf').onsubmit=e=>{e.preventDefault();const v=$('#pc').value.trim().toUpperCase();if(v==='MIZU10'){promo=v;db.set('mizu-promo',[v]);toast('Promo applied.')}else toast('That code is not valid.');draw()};$('#co').onclick=()=>toast('Demo store: checkout is not connected.')};
 root.onclick=e=>{const d=e.target.closest('[data-d]'),r=e.target.closest('[data-r]'),c=cart.get();if(d){c[+d.dataset.i].qty=Math.max(1,c[+d.dataset.i].qty+ +d.dataset.d);cart.set(c);draw()}if(r){c.splice(+r.dataset.r,1);cart.set(c);toast('Removed from cart.');draw()}};draw()},
recipes(){const g=$('#rg');g.innerHTML=RECIPES.map(r=>`<button class="rc card" data-r="${r.id}" aria-haspopup="dialog"><div class="media"><span class="a">${art({c:r.c,item:'bowl',name:r.name},1)}</span></div><div class="info"><div><h3>${r.name}</h3><p class="small muted">${r.time} · ${r.diff}</p></div><span class="small">View recipe →</span></div></button>`).join('');
 g.onclick=e=>{const b=e.target.closest('[data-r]');if(!b)return;const r=RECIPES.find(x=>x.id==b.dataset.r);lastFocus=b;const m=$('#modal');m.innerHTML=`<div class="mbox" role="dialog" aria-modal="true" aria-labelledby="mt"><button class="ib x" id="mx" aria-label="Close recipe">✕</button><div style="min-height:260px">${art({c:r.c,item:'bowl',name:r.name},1)}</div><div class="body"><h2 id="mt" style="font-size:2.6rem">${r.name}</h2><p class="muted">${r.time} · ${r.diff}</p><h3 style="margin-top:1rem">Ingredients</h3><ul>${r.ing.map(i=>`<li>${i}</li>`).join('')}</ul><h3>Instructions</h3><ol>${r.steps.map(i=>`<li>${i}</li>`).join('')}</ol></div></div>`;m.classList.add('open');$('#mx').onclick=closeModal;$('#mx').focus()};
 $('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}},
ritual(){const S=[['Scoop','Take two grams — about two bamboo scoops — of matcha.'],['Sift','Press through a fine sieve into a warm bowl. No clumps, no bitterness.'],['Add water','Pour 60–70ml of water at 70–80°C. Hotter water burns the leaf.'],['Whisk','Whisk in a quick W motion for 15 seconds until a fine foam forms.'],['Enjoy','Drink within a minute, while the foam is soft and the aroma is open.']];
 $('#steps').innerHTML=S.map((s,i)=>`<section class="step" data-i="${i}" aria-label="Step ${i+1}: ${s[0]}"><span class="n">0${i+1}</span><h2>${s[0]}</h2><p class="lead muted" style="margin-top:1rem">${s[1]}</p></section>`).join('');
 const v=$('#vis'),k=['<ellipse cx="200" cy="320" rx="90" ry="14" fill="#C9AE80"/><path d="M150 320q50-100 100 0z" fill="#66793A"/>','<ellipse cx="200" cy="200" rx="100" ry="16" fill="#C9AE80"/><path d="M110 200l40 60h100l40-60" fill="none" stroke="#4A3B30" stroke-width="3"/><path d="M200 270v70" stroke="#66793A" stroke-width="3" stroke-dasharray="4 8"/>','<path d="M110 280q10 100 90 100t90-100z" fill="#4A3B30"/><path d="M200 90q-10 60 0 120" stroke="#A9B592" stroke-width="8" fill="none"/><ellipse cx="200" cy="280" rx="90" ry="14" fill="#8CA050"/>','<path d="M110 280q10 100 90 100t90-100z" fill="#4A3B30"/><ellipse cx="200" cy="280" rx="90" ry="14" fill="#7E9444"/><g class="whisk"><rect x="190" y="40" width="20" height="90" rx="8" fill="#C9AE80"/><path d="M190 130q-30 40-26 100h72q4-60-26-100z" fill="#E1CCA1"/></g>','<path d="M110 280q10 100 90 100t90-100z" fill="#4A3B30"/><ellipse cx="200" cy="280" rx="90" ry="14" fill="#9BB06A"/><path d="M170 220q10-20 0-40M200 220q10-20 0-40M230 220q10-20 0-40" stroke="#8a8a7a" fill="none" opacity=".5"/>'];
 v.innerHTML=k.map(x=>scene('',x).replace('<svg','<svg class="'+'"')).join('');const dots=$('#dots');dots.innerHTML=S.map(()=>'<i></i>').join('');
 const set=i=>{$$('svg',v).forEach((s,j)=>s.classList.toggle('on',j===i));$$('i',dots).forEach((d,j)=>d.classList.toggle('on',j<=i))};set(0);
 const io=new IntersectionObserver(es=>es.forEach(e=>{e.target.classList.toggle('on',e.isIntersecting);if(e.isIntersecting)set(+e.target.dataset.i)}),{rootMargin:'-45% 0px -45% 0px'});$$('.step').forEach(s=>io.observe(s));
 const c=$('#cups'),calc=()=>{const n=+c.value;$('#oc').textContent=n;$('#og').textContent=2*n+'g';$('#ow').textContent=60*n+'–'+70*n+'ml'};c.oninput=calc;calc()},
story(){$$('[data-scene]').forEach(el=>el.innerHTML=SCENES[el.dataset.scene]('#66793A'));
 const f=$('#cf');f.onsubmit=e=>{e.preventDefault();let ok=true;$$('[data-req]',f).forEach(i=>{const bad=!i.value.trim()||(i.type==='email'&&!/^\S+@\S+\.\S+$/.test(i.value));i.nextElementSibling.textContent=bad?i.dataset.req:'';i.setAttribute('aria-invalid',bad);if(bad)ok=false});if(ok){toast('Message sent. We reply within two days.');f.reset()}}}};
let lastFocus;function closeModal(){const m=$('#modal');if(m&&m.classList.contains('open')){m.classList.remove('open');lastFocus&&lastFocus.focus()}}
/* ---------- shared: newsletter + reveal ---------- */
function extras(){const n=$('#nlf');if(n)n.onsubmit=e=>{e.preventDefault();const i=$('input',n),ok=/^\S+@\S+\.\S+$/.test(i.value);$('.err',n.parentNode).textContent=ok?'':'Enter a valid email, like you@example.com.';if(ok){toast('Welcome to the ritual.');n.reset()}};
 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.15});$$('.rv,.reveal-img').forEach(el=>io.observe(el))}
document.addEventListener('DOMContentLoaded',()=>{layout();behaviours();badges();const p=pages[document.body.dataset.page];p&&p();extras()});
